# Generated by Django 4.2.6 on 2023-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_institution_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
