# Generated by Django 4.2.6 on 2023-10-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_teamgame_min_t_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AddField(
            model_name="studentgamecategory",
            name="teacher",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.teacher",
            ),
        ),
    ]
