# Generated by Django 4.2.6 on 2023-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_teamparticipant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="team",
        ),
    ]
